POST http://phpapi/chapter1/index.php/user/ HTTP/1.1
Content-Type: application/json

{
    "user_email": "test@test.ch",
    "user_name": "Test"
}

###

GET http://phpapi/chapter1/index.php/user/14 HTTP/1.1

###

DELETE http://phpapi/chapter1/index.php/user/14 HTTP/1.1

###

GET http://phpapi/chapter1/index.php/user/14 HTTP/1.1